---
title: "Drosophila"
author: "Cescily Metzgar"
date: "1/26/2017"
output: bookdown::html_document2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PASWR2)
library(dplyr)
```

```{r, f, fig.cap = "Histogram of `fecundity`", echo = FALSE}

ggplot(data = DROSOPHILA, aes(fecundity)) +
  geom_histogram(fill = "pink", binwidth = 4) + 
  theme_bw()

```

# Testing Hypotheses {-}

$H_0: \mu_{\textrm{nonselected}} - \mu_{\textrm{resistant}} = 0$

$H_A: \mu_{\textrm{nonselected}} - \mu_{\textrm{resistant}} \neq 0$


```{r}





Res <- DROSOPHILA %>%
  filter(line != "Susceptible") %>%
  group_by(line) %>%
  summarize(MF = mean(fecundity), SF = sd(fecundity), n = n())
Res

D <- DROSOPHILA %>%
  filter(line != "Susceptible")
D


t.test(fecundity ~ line, data = D)

xbar1 <- Res[1, 2]
xbar2 <- Res[2, 2]
s1 <- Res[1, 3]
s2 <- Res[2, 3]
n1 <- Res[1, 4]
n2 <- Res[2, 4]
TS <- (xbar1 - xbar2)/(s1^2/n1 + s2^2/n2)^0.5
names(TS) <- "TestStatistic"
TS
str(TS$TestStatistic)
nu <- (s1^2/n1 + s2^2/n2)^2 / ((s1^2/n1)^2/(n1-1) + (s2^2/n2)^2/(n2-1))
names(nu) <- "DegreesOfFreedom"
nu

ts <- TS$TestStatistic
ts
nu <- nu$DegreesOfFreedom
nu
pvalue <- pt(ts, nu, lower = FALSE)
pvalue




N <- 10^4 - 1
PTS <- numeric(N)
for(i in 1:N){
  PTS[i] <- t.test(fecundity ~ sample(line), data = D)$stat
}
epv <- (sum(PTS >= ts) + 1)/(N + 1)
epv
ggplot(data = data.frame(x = PTS), aes(x = x)) +
  geom_density(fill = "purple") + 
  theme_bw()

```